name: Bug Report
description: Report a bug to be fixed
title: "[Bug] "
labels: ["workflow/available", "bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What's wrong?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - medium
        - high
        - critical
        - low
